# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:title 
auto: true
pygments: true
markdown: rdiscount
var:
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  rss_path: /atom.xml

production_url : http://tivon.me # or your custom domain name
title : Tivon

author :
  name : Tivon

exclude: .rbenv-version
