title: Void
url:              # Site url.
disqus_shortname: mage3k
google_analytics: UA-50515985-1
links:
  - name: about
    url: /about
highlighter: true
permalink: pretty
markdown: redcarpet
redcarpet:
  extensions:
    - smart
posts_limit: 5
